### ISSUE TITLE
rttest example build error

### ISSUE THREAD

**Issue by flobotics** [ros2/rttest#9]
i, i try to use https://github.com/ros2/rttest , but when i want to build the examples, it returns errors when running make:

rttest/build/include/rttest/rttest.h:29:21: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘=’ token
   size_t iterations = 0,
                     ^

and some other lines with the same style of error ? in rttest.h is a struct, with the first entry with the line of above error ?

including stddef.h or changing size_t to unsigned int, doesnt change anything from the style of error ?

thanks for help flo

**Comment by jacquelinekay** [comment]
Are you building the code with ament or pure cmake? And which platform are you building on?

**Comment by flobotics** [comment]
i build with pure cmake, as the tutorial says.  I build it on ubuntu 15.4

**Comment by jacquelinekay** [comment]
Hmm, the pure CMake build on master currently works for me, but I've only tested on 14.04. It maybe a problem with different version of GCC (or Clang).

**Comment by flobotics** [comment]
ok, because its in alpha stage, i test it on 14.04

**Comment by flobotics** [comment]
i installed 14.04 64bit, and run into the same error ?  here is the history of my  commands : 

50  git clone https://github.com/ros2/rttest.git
   51  cd rttest/
   52  ls
   53  mkdir build
   54  cd build/
   55  sudo apt-get install cmake
   56  cmake ..
   57  cmake .. -DCMAKE_INSTALL_PREFIX=./
   58  make install
   59  cd ../examples/
   60  mkdir build
   61  cd build/
   62  cmake .. -DCMAKE_INSTALL_PREFIX=./
   63  make

thannks for help

**Comment by jacquelinekay** [comment]
I've got the problem. Our CI wasn't testing the package with C linkage, which is what the example requires. Somewhere down the road I changed the API to pass variables by reference, which is not a feature C supports. I still want this library to be C compatible, so the example should be fixed in this upcoming PR, which I hope to get merged within the next few days: https://github.com/ros2/rttest/pull/8

In the meantime, you can try using ament to build code with rttest, since the ament build is tested and working.

**Comment by jacquelinekay** [comment]
@flobotics Can you update your repositories and try a source build again?

**Comment by flobotics** [comment]
now it builds fine:

 ./example_loop 
Initial major pagefaults: 0
Initial minor pagefaults: 495
No results filename given, not writing results
rttest statistics:
  - Minor pagefaults: 1
  - Major pagefaults: 0
  Latency (time after deadline was missed):
    - Min: 2420 ns
    - Max: 28732 ns
    - Mean: 11713.4 ns
    - Standard deviation: 826.704


thanks

**Comment by jacquelinekay** [comment]
Great, thank you for testing!

**Comment by flobotics** [comment]
no problem
